[package]
name = "desktop"
version = "0.1.0"
edition = "2021"
build="build.rs"

[dependencies]
chip8_core = { path = "../chip8_core" }

[dependencies.sdl2]
version = "*"
features = ["use_mac_framework"]